#!/bin/bash

./configure target="csc688" \
               cflags="-I. -I./offline -O3 -Wno-deprecated -fPIC" \
               lflags="" \
               ignore="'viz/*' 'viz/plot/*'" \
               bin="build/offline_csc688"
