#!/bin/bash

./configure target="csc688" \
               cflags="-I. -I./offline -DOFFLINE  -ggdb -Wno-deprecated -fPIC" \
               lflags="" \
               ignore="" \
               bin="build/csc688_offline"
